# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: alex-os
description: An atomic, rolling-release operating system with an immutable desktop environment, one-click theme switching, and containerized package support.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - distrobox
        - git
        - python3-pyqt6
        - fastfetch
        - wine

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.google.Chrome
          - com.valvesoftware.Steam
          - io.github.kolunmi.Bazaar
      - scope: user

  - type: signing
