name: Build alex-os
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  bluebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear space
        uses: hastd/free-disk-space@main

      - name: Build Image
        uses: blue-build/github-action@v1.12
        with:
          recipe: 'recipe.yml'
          build_opts: '--no-sign'
          registry_token: ${{ secrets.GITHUB_TOKEN }}
